POST http://localhost:3000/product


{
    "productName":"Nike - 95",
    "price": 149.99,
    "quantity": 1
}

###

GET http://localhost:3000/product

###

PUT http://localhost:3000/product/62e968f39cebf1e4c467971b

{
    "productName":"shoes",
    "price": 109.90,
    "quantity":10
}

###

POST http://localhost:3000/basket

{
    "items":[]
}

###

GET http://localhost:3000/basket/62ea53aa131f0e12046a8107

###

POST http://localhost:3000/basket/62ea553f131f0e12046a8108


{
    "_id":"1",
    "productName":"pooes2",
    "quantity": 1,
    "price": 14.99
}

###

POST http://localhost:3000/checkout/62ea5126131f0e12046a8104


###

GET http://localhost:3000/order/62ea5138131f0e12046a8105

###

POST http://localhost:3000/order/62ea5138131f0e12046a8105