POST http://localhost:3000/product


{
    "productName":"shoes",
    "price": 10.99,
    "quantity": 1
}

###

GET http://localhost:3000/product

###

PUT http://localhost:3000/product/62e968f39cebf1e4c467971b

{
    "productName":"shoes",
    "price": 109.90,
    "quantity":10
}

###

POST http://localhost:3000/basket

{
    "items":[]
}

###

GET http://localhost:3000/basket/62e9942df55a3425b876d3f2

###

PUT http://localhost:3000/basket/62e99519f41e373d0f4ead7b

{
    "items":[
        {
            "productName":"shoes"
        },
        {
            "productName":"feet"
        }
    ]
}

###

POST http://localhost:3000/checkout/62e994a2f41e373d0f4ead7a