POST http://localhost:8000/basket

{
    "Id":"1",
    "Items":[
        {
            "id":"1",
            "productName":"shoe",
            "price":10.99,
            "quantity":1
        }
    ]
}

###

GET http://localhost:8000/basket/62