POST http://localhost:8000/product

{
    "id":"1",
    "ProductName":"Pooes",
    "price":113.43
}

###

GET http://localhost:8000/product 

###

DELETE http://localhost:8000/product

###

GET http://localhost:8000/product/9
